---

- name: ansible-role-etcd
  src: git+https://github.com/githubixx/ansible-role-etcd.git

- name: ansible-role-docker
  src: git+https://github.com/geerlingguy/ansible-role-docker.git

- name: ansible-role-ssl-certs
  src: git+https://github.com/jdauphant/ansible-role-ssl-certs.git
