---

- name:  site.yaml | All roles
  hosts: all
  become: True
  become_user: root

  roles:

- name:  site.yaml | MySQL Server roles
  hosts: mysqld
  become: True
  become_user: root

  roles:
    - mysqld

- name: site.yaml | SSL Certs roles
  hosts: all
  become: True
  become_user: root

  roles:
    - ansible-role-ssl-certs

- name: Include etcd play
  include: etcd.yaml

- name: Include docker play 
  include: docker.yaml

- name: Include nodejs play
  include: nodejs.yaml

